[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="users" type="ru.itmo.tpl.model.User[]" --]
[#-- @ftlvariable name="user" type="ru.itmo.tpl.model.User" --]
[#-- @ftlvariable name="header_links" type="ru.itmo.tpl.model.Link[]" --]
[#-- @ftlvariable name="uri" type="java.lang.String" --]
[#-- @ftlvariable name="posts" type="ru.itmo.tpl.model.Post[]" --]